# these should probably go in their own package to share with cronie?
#TODO should these go into a different fcron-croncompat package? IMO too finnicky. Ideally, do the thing where it installs by default but !fcron-croncompat works
d /etc/cron.d 0755 root root -
d /etc/cron.hourly 0755 root root -
d /etc/cron.daily 0755 root root -
d /etc/cron.weekly 0755 root root -
d /etc/cron.monthly 0755 root root -

C /etc/fcron/fcron.allow 0640 root _fcron - /usr/share/fcron/fcron.allow
C /etc/fcron/fcron.deny 0640 root _fcron - /usr/share/fcron/fcron.deny
C /etc/fcron/fcron.conf 0640 root _fcron - /usr/share/fcron/fcron.conf

d /var/spool/fcron 6770 _fcron _fcron -
